export class CSVRecord {
    public fecha : any ;
    public ID :  any;
    public	PLAN_FTTH : any;
    public	TIPODOCUMENTID : any;
    public DOCUMENTID : any;
    public	NOMBRE : any;
    public	CELULAR : any;
    public	CORREO : any;
    public	DIRECCION : any; 
    public	BARRIO : any;
    public	FECHA_ENT : any;
    public	FECHA_INST : any;
    public	ASESOR : any;
    public	WIFI : any;
    public	CLAVE : any;
    public	EQUIPO : any;
    public	ESTADO : any;
    public	COMENT : any;
    public	CORTES : any;
    public	REFERENCIA_DE_PAGO : any;
    public	ZONA : any;																						
}